// All RTP Roles for OBPS V2
export const RTPS = [
    "BPA_ARCHITECT",
    "BPA_BUILDER",
    "BPA_ENGINEER",
    "BPA_STRUCTURALENGINEER",
    "BPA_TOWNPLANNER",
    "BPA_SUPERVISOR",
    "BPA_GEO_TECH_ENGINEER",
    "BPA_CIVIL_ENGINEER",
    "BPA_UTILITY_ENGINEER",
    "BPA_LANDSCAPE_ARCHITECT",
    "BPA_GROUP_AGENCY",
    "BPA_URBAN_DESIGNER",
    "BPA_RTP"
]

Digit.RTPS = RTPS;
